# Generated by Django 5.2.5 on 2025-08-12 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_img', models.FileField(upload_to='pictures')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.dept_tbl')),
            ],
        ),
    ]
