# Generated by Django 5.2.5 on 2025-08-18 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0003_reg_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('test', models.CharField(max_length=40)),
                ('doctor_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management_app.reg_tbl')),
            ],
        ),
    ]
